project:
  type: website

website:
  title: "Portfolio"
  favicon: "may_logo.png"
  page-footer:
    center: |
      [Contact May Halfon](https://mail.google.com/mail/?view=cm&to=mayhalfon05@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org/)
    right:
       - icon: linkedin 
         href:  https://www.linkedin.com/in/may-halfon-163782289/
    background: "#40798C"
  
  
  navbar:
    background: "#40798C"
    left: 
      - text: Home
        href: index.qmd
      - text: Attrition Analysis
        href: ibm_dataset/index.qmd
      - text: Resume
        href: resume.qmd
    right:
       - icon: linkedin
         href: https://www.linkedin.com/in/may-halfon-163782289/
        #href: https://www.linkedin.com/in/may-halfon-163782289/
      #- icon: twitter
       # href: https://twitter.com
        
format:
  html:
    theme: 
      light: litera
      dark: [litera, theme_dark_custom.scss]
    code-link: true
    code-fold: show
    #code-tools: true
    code-block-bg: "#f5f7fa"
    code-block-border-left: "#40798C"
    highlight-style: GitHub
    linkcolor: "black"
    css: styles.css



