project:
  type: website

website:
  title: "Portfolio"
  favicon: "may_logo.png"
  navbar:
    background: "#40798C"
    left: 
      - text: Home
        href: index.qmd
      - text: Projects
        href: test.qmd
      - text: Resume
        href: posts/resume.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        
format:
  html:
    theme: 
      light: litera
      dark: [litera, theme_dark_custom.scss]
    code-link: true
    code-fold: show
    code-tools: true
    #code-block-bg: "#f5f7fa"
    #code-block-border-left: "#40798C"
    highlight-style: breeze
    css: styles.css

editor: visual

